/**
 * Production Notion Mutation Wiring Specification (Phase 2C Preparation for Phase 2D)
 *
 * ARCHITECTURAL SAFETY INVARIANT:
 * This file specifies and documents the required wiring, security gates, and interfaces
 * for the future production mutation adapter (Phase 2D).
 *
 * IT IS STRICTLY DISCONNECTED IN PHASE 2C:
 * - NOT instantiable in any Phase 2C CLI or script.
 * - NOT exported by any apply script (apply scripts do not exist in Phase 2C).
 * - NOT connected to BackfillExecutor.execute().
 * - Real live Notion DML mutations remain 100% blocked and physically unavailable.
 */

import { BackfillNotionAdapter } from './backfill-adapter';

export interface ProductionWiringPreconditions {
  /** Path to the read-only authorization artifact generated by Phase 2C */
  preflightArtifactPath: string;
  /** Maximum acceptable age for the preflight authorization (default: 15 minutes = 900,000 ms) */
  maxPreflightAgeMs: number;
  /** Required value for the safety gate variable FINANCIAL_BACKFILL_ENABLED */
  expectedSafetyGateValue: 'I_UNDERSTAND_BACKFILL_MUTATIONS';
  /** Path to the isolated local production journal */
  journalPath: string;
}

export const PRODUCTION_WIRING_SPEC: ProductionWiringPreconditions = {
  preflightArtifactPath: '.local/backfill-live-preflight.json',
  maxPreflightAgeMs: 15 * 60 * 1000, // 15 minutes TTL
  expectedSafetyGateValue: 'I_UNDERSTAND_BACKFILL_MUTATIONS',
  journalPath: '.local/backfill-live-journal.db',
};

/**
 * Interface contract required for Phase 2D production mutation adapter.
 * When implemented in Phase 2D under explicit operator authorization, it must:
 * 1. Verify all ProductionWiringPreconditions before instantiating.
 * 2. Record every write request attempt in BackfillJournal BEFORE sending the network call.
 * 3. Enforce rate limiting respecting HTTP 429 Retry-After headers and 5xx exponential backoff.
 * 4. Verify read-back properties and record fingerprints before marking VERIFIED.
 * 5. Strictly enforce MAX_NEW_PAGES_BUDGET = 159.
 */
export interface ProductionNotionMutationAdapterContract extends BackfillNotionAdapter {
  readonly isProductionMutationAuthorized: boolean;
  readonly targetWorkspaceIdentityHash: string;
}
